#ifndef YUGGOTH_GRAPHICS_TYPES_H
#define YUGGOTH_GRAPHICS_TYPES_H

#include "structure_tools.h"
#include <vma/vk_mem_alloc.h>

namespace Yuggoth {

enum class AllocationCreateMaskBits {
  E_DEDICATED_MEMORY_BIT = VMA_ALLOCATION_CREATE_DEDICATED_MEMORY_BIT,
  E_NEVER_ALLOCATE_BIT = VMA_ALLOCATION_CREATE_NEVER_ALLOCATE_BIT,
  E_MAPPED_BIT = VMA_ALLOCATION_CREATE_MAPPED_BIT,
  E_UPPER_ADDRESS_BIT = VMA_ALLOCATION_CREATE_UPPER_ADDRESS_BIT,
  E_DONT_BIND_BIT = VMA_ALLOCATION_CREATE_DONT_BIND_BIT,
  E_WITHIN_BUDGET_BIT = VMA_ALLOCATION_CREATE_WITHIN_BUDGET_BIT,
  E_CAN_ALIAS_BIT = VMA_ALLOCATION_CREATE_CAN_ALIAS_BIT,
  E_HOST_ACCESS_SEQUENTIAL_WRITE_BIT = VMA_ALLOCATION_CREATE_HOST_ACCESS_SEQUENTIAL_WRITE_BIT,
  E_HOST_ACCESS_RANDOM_BIT = VMA_ALLOCATION_CREATE_HOST_ACCESS_RANDOM_BIT,
  E_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT = VMA_ALLOCATION_CREATE_HOST_ACCESS_ALLOW_TRANSFER_INSTEAD_BIT,
  E_STRATEGY_MIN_MEMORY_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT,
  E_STRATEGY_MIN_TIME_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_TIME_BIT,
  E_STRATEGY_MIN_OFFSET_BIT = VMA_ALLOCATION_CREATE_STRATEGY_MIN_OFFSET_BIT
};

using AllocationCreateMask = Mask<AllocationCreateMaskBits>;

ImageAspectMask GetAspectMask(Format format);
AccessMask2 GetAccessMaskFromLayout(ImageLayout layout, bool destination);
PipelineStageMask2 GetPipelineStageMaskFromLayout(ImageLayout layout, bool destination);

} // namespace Yuggoth

#endif // YUGGOTH_GRAPHICS_TYPES_H